Use postmessage instead of storage event for embedded case
SeeClickFix/torii pull request #2
Opened 2024-08-20 20:48 UTC by Gaurav0

2024-09-03 18:21 UTC, AndrewHYi requested changes

2024-09-03 18:21 UTC, AndrewHYi commented on addon/mixins/ui-service-mixin.js
> +      // Using postMessage as an alternative to localStorage/storageEvent
Let's add some updated tests  - QA is getting pretty crazy https://civicplus.tpondemand.com/entity/179336-open-new-window-vs-modal-popup/comments/309113.

2024-09-19 21:18 UTC, AndrewHYi requested changes
suggestion: Is there a way we can run/update the torii tests?

2024-09-20 13:47 UTC, zbeat commented
TP story link:
https://civicplus.tpondemand.com/entity/179336-open-new-window-vs-iframe-modal

We need to fix the TP<>Github integration permissions, so all SCF repos are included.

2024-09-20 14:04 UTC, Gaurav0 commented
@AndrewHYi Tests are running automatically.

2024-09-20 14:06 UTC, AndrewHYi commented
@Gaurav0 nice, looks like existing tests pass - should we add tests for the new updates scenarios?

2024-09-23 15:09 UTC, AndrewHYi commented on addon/mixins/ui-service-mixin.js
> +      // Using postMessage as an alternative to localStorage/storageEvent
NIce, tests!

2024-09-23 15:13 UTC, AndrewHYi requested changes

2024-09-23 15:13 UTC, AndrewHYi commented on addon/mixins/ui-service-mixin.js
> +        if (messageEvent.data === 'getPendingRequestKey') {
suggestion: this fix should be merged alongside the first commit. Also, the commit about feature flags is confusing here, but that only makes sense in the context of the SCF application (not here in Torii fork land).

2024-09-23 15:13 UTC, AndrewHYi commented on package.json
> +  "version": "1.0.0-beta.3",
suggestion: the version bump should be the last commit - also, do we need to bump the version up again?

2024-09-23 15:13 UTC, AndrewHYi commented on tests/unit/mixins/ui-service-mixin-test.js
> +import EmberObject from '@ember/object';
suggestion: let's add the test to the first commit.

thought: I need some help walking through the test code - I'll schedule something for this afternoon.

2024-09-23 17:20 UTC, AndrewHYi approved these changes

2024-09-23 17:22 UTC, merged